name: Static Analysis

on: [pull_request, push]

jobs:
  larastan:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Install composer dependencies
        run: composer install --no-scripts

      - name: Run Larastan
        run: vendor/bin/phpstan analyse
